- name: Push Docker image to ECR
  hosts: localhost
  vars:
    aws_region: eu-west-1
    ecr_repo: chatbot-lambda
    aws_account_id: 9318
  tasks:
    - name: Login to ECR
      command: >
        aws ecr get-login-password --region {{ aws_region }} |
        docker login --username AWS --password-stdin {{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com

    - name: Tag and push
      command: >
        docker tag my-lambda-function:latest {{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ ecr_repo }}:latest &&
        docker push {{ aws_account_id }}.dkr.ecr.{{ aws_region }}.amazonaws.com/{{ ecr_repo }}:latest
